-- MySQL Script generated by MySQL Workbench
-- Tue 10 Nov 2020 07:51:59 AM CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- This script creates/defines our database

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bizapp3
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bizapp3` ;

-- -----------------------------------------------------
-- Schema bizapp3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bizapp3` ;
USE `bizapp3` ;

-- -----------------------------------------------------
-- Table `bizapp3`.`stocks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bizapp3`.`stocks` (
  `symbol` VARCHAR(10) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `current_price` DOUBLE NOT NULL,
  `price_change` DOUBLE NOT NULL,
  `percent_change` DOUBLE NOT NULL,
  `bid_value` DOUBLE NULL,
  `bid_amount` INT UNSIGNED NULL,
  `ask_value` DOUBLE NULL,
  `ask_amount` INT UNSIGNED NULL,
  `market_cap` BIGINT UNSIGNED NULL,
  `pe_ratio` DOUBLE NULL,
  `eps` DOUBLE NULL,
  `dividend` DOUBLE NULL,
  `yield` DOUBLE NULL,
  `beta` DOUBLE NULL,
  UNIQUE INDEX `symbol_UNIQUE` (`symbol` ASC) VISIBLE,
  PRIMARY KEY (`symbol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bizapp3`.`stock_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bizapp3`.`stock_history` (
  `symbol` VARCHAR(10) NOT NULL,
  `date` DATE NOT NULL,
  `open` DOUBLE NOT NULL,
  `close` DOUBLE NOT NULL,
  `high` DOUBLE NOT NULL,
  `low` DOUBLE NOT NULL,
  `volume` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`symbol`, `date`),
  CONSTRAINT `stock_sh_fk`
    FOREIGN KEY (`symbol`)
    REFERENCES `bizapp3`.`stocks` (`symbol`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bizapp3`.`stock_tracker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bizapp3`.`stock_tracker` (
  `symbol` VARCHAR(10) NOT NULL,
  `market_time` DATETIME NOT NULL,
  `price` DOUBLE NOT NULL,
  PRIMARY KEY (`symbol`, `market_time`),
  CONSTRAINT `stock_st_fk`
    FOREIGN KEY (`symbol`)
    REFERENCES `bizapp3`.`stocks` (`symbol`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bizapp3`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bizapp3`.`users` (
  `username` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bizapp3`.`stocks_following`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bizapp3`.`stocks_following` (
  `username` VARCHAR(50) NOT NULL,
  `symbol` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`username`, `symbol`),
  INDEX `symbol_sf_fk_idx` (`symbol` ASC) VISIBLE,
  CONSTRAINT `stock_sf_fk`
    FOREIGN KEY (`symbol`)
    REFERENCES `bizapp3`.`stocks` (`symbol`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `user_sf_fk`
    FOREIGN KEY (`username`)
    REFERENCES `bizapp3`.`users` (`username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bizapp3`.`cryptos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bizapp3`.`cryptos` (
  `symbol` VARCHAR(15) NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `current_price` DOUBLE NOT NULL,
  `price_change` DOUBLE NOT NULL,
  `percent_change` DOUBLE NOT NULL,
  `market_cap` BIGINT UNSIGNED NOT NULL,
  `circulating_supply` BIGINT UNSIGNED NOT NULL,
  UNIQUE INDEX `symbol_UNIQUE` (`symbol` ASC) VISIBLE,
  PRIMARY KEY (`symbol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bizapp3`.`crypto_tracker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bizapp3`.`crypto_tracker` (
  `symbol` VARCHAR(15) NOT NULL,
  `market_time` DATETIME NOT NULL,
  `price` DOUBLE NOT NULL,
  PRIMARY KEY (`symbol`, `market_time`),
  CONSTRAINT `crypto_ct_fk`
    FOREIGN KEY (`symbol`)
    REFERENCES `bizapp3`.`cryptos` (`symbol`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bizapp3`.`crypto_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bizapp3`.`crypto_history` (
  `symbol` VARCHAR(15) NOT NULL,
  `date` DATE NOT NULL,
  `open` DOUBLE NOT NULL,
  `close` DOUBLE NOT NULL,
  `high` DOUBLE NOT NULL,
  `low` DOUBLE NOT NULL,
  `volume` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`symbol`, `date`),
  CONSTRAINT `crypto_ch_fk`
    FOREIGN KEY (`symbol`)
    REFERENCES `bizapp3`.`cryptos` (`symbol`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bizapp3`.`cryptos_following`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bizapp3`.`cryptos_following` (
  `username` VARCHAR(50) NOT NULL,
  `symbol` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`username`, `symbol`),
  INDEX `user_cf_fk_idx` (`symbol` ASC) VISIBLE,
  CONSTRAINT `symbol_cf_fk`
    FOREIGN KEY (`symbol`)
    REFERENCES `bizapp3`.`cryptos` (`symbol`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `user_cf_fk`
    FOREIGN KEY (`username`)
    REFERENCES `bizapp3`.`users` (`username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
